Keyboard handling improvements
OpenRTX/OpenRTX pull request #306
Opened 2024-12-29 23:08 UTC by sp6hfe

This PR extend support for keyboard handling.

By resigning from (not used) KEY_F6 support 4 button events are accessible to get more grained TRX control.
Previous implementation allowed to differentiate between a press and long press (no support for single/multi-press and repeats)

Based on timings it is possible to detect
- a press (a key/keys press detected since last keyboard scan)
- a single-key long press (key depressed for some time)
- a multi-key long press (1+ keys depressed for some time)
- a repeat (which is a periodic event that happens after long press, but reserved for single keys only)

The idea behind is at first to distinguish between single/long presses and repeats to not widely take an action when we don't want to. Secondly a long multi-press event is useful for some special actions requiring keys combination (like entering a hidden menu or enabling/disabling an option/taking a defined action). Events allow for quick filtering of them when needed.

Knob movements are handled in parallel and due to the nature of the knob change signal (can not be detected as long press or repeat) is not involved much into the keyboard events logic. If you want to use knob direction just look up them in an event pressed keys.

Multi-key support is working by default in a way that whenever an additional (1+) key is pressed no event is generated until the long-press timeout occur. If any additional key is pressed before long-press is detected a timer restarts and upcoming long-press event (multi-press) will report all the keys pressed.
Max number of multi-pressed keys is 3. When more is detected there will be no further action until keyboard is fully released.
If during multi-press a change is detected by lowering number of pressed keys or by keeping the same amount but in a different combination no further action is possible until keyboard is fully released.

Additionally a special mode was added due to how Macro Menu handling is currently implemented. It is possible to generate press events for each newly depressed key when already in a multi-key situation. This allow for changing macro options without actually latching the menu itself.

Improvements proposed in this PR fix some behaviors detected like:
- pressing long a digit in VFO mode would add 2 digits to the frequency entering form instead of 1,
- pressing long up/down in the menus change menu position by 2 instead of that many as long as button is kept pressed,
- pressing ENTER long advances in sub-menus by 2 instead of 1,
- pressing and holding F2 latches Macro Menu even though it is used with a combination with a digit to quickly change an option without actually a need to latch it.

2025-01-06 19:58 UTC, silseva requested changes

2025-01-06 19:58 UTC, silseva commented on openrtx/include/core/input.h
> +void input_allowPressEventOnMultilpeKeysPressed(bool isPressEventAllowed);
I'd rename this to `input_enableMultiKeyEvent` to reduce verbosity

2025-01-06 19:58 UTC, silseva commented on openrtx/include/core/input.h
> +bool processKnobMovementDetection(keyboard_t keys, kbd_msg_t* msg);
The `input_` prefix is missing. I also suggest to rename this to `input_handleKnobEvents` or something similar

2025-01-06 19:58 UTC, silseva commented on openrtx/src/core/input.c
> +bool pressEventAllowedForMultipleKeys;
The `static` keyword and the comment are missing. Also, please reduce the verbosity. I suggest, for example, `multiKeyEvent`

2025-01-06 19:58 UTC, silseva commented on openrtx/src/core/input.c
> +    const bool isKeyboardEvent = true;      // Return value
I'd just return true/false instead of wrapping these into const variables

2025-01-06 19:58 UTC, silseva commented on openrtx/src/core/input.c
> +    static keyboard_t previousKeys      = 0;     // Previously pressed keys
Please avoid defining static variables inside the function, if possible. These should be moved at the beginning of the file.

2025-01-06 20:59 UTC, sp6hfe commented on openrtx/src/core/input.c
> +    static keyboard_t previousKeys      = 0;     // Previously pressed keys
Intention here is to narrow the scope. input_scanKeyboard is the only user and it should be like that but I see your point in having all the globals in one place. Upcoming C++ class (separate PR) would handle scoping in a proper way.

2025-01-06 21:00 UTC, sp6hfe commented on openrtx/src/core/input.c
> +    const bool isKeyboardEvent = true;      // Return value
Agree. This is my habit from C++ where for readability I use lots of static constexpr.

2025-01-07 17:01 UTC, silseva commented
@sp6hfe if you can please fix the various issues, I'll then proceed with merging the PR :)

2025-01-07 22:50 UTC, sp6hfe commented on openrtx/include/core/input.h
> +void input_allowPressEventOnMultilpeKeysPressed(bool isPressEventAllowed);
fixed

2025-01-07 22:50 UTC, sp6hfe commented on openrtx/include/core/input.h
> +bool processKnobMovementDetection(keyboard_t keys, kbd_msg_t* msg);
fixed

2025-01-07 22:50 UTC, sp6hfe commented on openrtx/src/core/input.c
> +bool pressEventAllowedForMultipleKeys;
fixed

2025-01-07 22:50 UTC, sp6hfe commented on openrtx/src/core/input.c
> +    const bool isKeyboardEvent = true;      // Return value
fixed

2025-01-07 22:51 UTC, sp6hfe commented on openrtx/src/core/input.c
> +    static keyboard_t previousKeys      = 0;     // Previously pressed keys
fixed

2025-01-09 11:30 UTC, sp6hfe commented
Pls check fixes

2025-01-18 08:57 UTC, silseva approved these changes

2025-01-18 08:57 UTC, merged